### ISSUE TITLE
Requirement: Get Start

### ISSUE THREAD

**Issue by ghost** [Mukosame/mukosame.github.io#6]
请问可否在readme.md中增加get start部分，介绍将代码clone下来之后如何操作，使得自己的主页可以成功展示（目前我的是404notfound了）

**Comment by Mukosame** [comment]
啊哈，刚刚看到你的页面已经上线了，而且还很不错呢！
最近没什么时间维护这个repo了，如果你能把自己成功fork的经验写下来，我很乐意给你链接+推荐！
